changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-release-notes
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - feature
        - enhancement
        - semver-minor
    - title: Bug Fixes
      labels:
        - bug
        - fix
        - semver-patch
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - ci
        - refactor
        - test
    - title: Other Changes
      labels:
        - "*"
