export const APP_PACKAGE_NAME = 'mde'
export const APP_PRODUCT_NAME = 'MDE'
export const CAPTURE_STARTUP_DIAGNOSTICS_ENV =
  'MDE_CAPTURE_STARTUP_DIAGNOSTICS'
export const DISABLE_SINGLE_INSTANCE_ENV = 'MDE_DISABLE_SINGLE_INSTANCE'
export const E2E_USER_DATA_PATH_ENV = 'MDE_E2E_USER_DATA_PATH'
export const STARTUP_DIAGNOSTICS_GLOBAL_KEY = '__mdeStartupDiagnostics'
